/*
 * data_model_snapshot.c
 * 
 * Snapshot of code generation data model.
 * This information is included in the executable file
 * and does not affect any memory content in the embedded device.
 */
 
__attribute__((section("diagnostics_cinfo, info"), keep)) char MCAF_data_model_snapshot[] =
  "{\"motor\": {\"Tfr\": 0.00205697696266,\"B\": 1.30626753966e-05,\"Lq\": 0.002088"
  "74870054,\"poleCount\": 10,\"rated_current\": 1.16,\"J\": 5.84054862552e-06,\"ve"
  "locity\": {\"nominal\": 327.249234749,\"maximum\": 366.519142919,\"units\": \"ra"
  "d\\/s\"},\"L\": 0.00216216874124,\"R\": 2.36163104505,\"current\": {\"maximum\":"
  " {\"continuous\": 1.16,\"peak\": 1.16},\"units\": \"A\"},\"Ld\": 0.0022355887819"
  "3,\"Ke\": 0.0422049891797,\"id\": \"Hurst100\"},\"controller\": {\"encoder\": {"
  "\"tracking_loop\": {\"zeta\": 1.5}},\"foc\": {\"feedback\": {\"voltage_delay\": "
  "0}},\"pll\": {\"delay_match\": true,\"properties\": {\"reference\": false},\"keI"
  "nverseScaling\": 1.0},\"operation\": {\"min_deceleration_time\": null},\"dyn_cur"
  "rent\": {\"maxgain\": 1.1},\"zsmt\": {\"errorLimit\": 0.99997,\"properties\": {"
  "\"independent\": true,\"reference\": false},\"duration\": {\"lockDelay\": 0.05},"
  "\"probe\": {\"accumGain\": 1.0}},\"fault_detect\": {\"recovery\": {\"attempts\":"
  " 3}}},\"metadata\": {\"MCC\": {\"architecture\": \"melody\",\"peripherals\": {\""
  "instances\": [{\"name\": \"ADC1\",\"type\": \"adc\"},{\"name\": \"PWM\",\"type\""
  ": \"pwm_hs\"},{\"name\": \"QEI1\",\"type\": \"qei\"},{\"name\": \"TMR1\",\"type"
  "\": \"timer\"},{\"name\": \"SCCP1\",\"type\": \"timer\"},{\"name\": \"UART1\",\""
  "type\": \"uart\"},{\"name\": \"OPA1\",\"type\": \"opa\"},{\"name\": \"OPA2\",\"t"
  "ype\": \"opa\"},{\"name\": \"OPA3\",\"type\": \"opa\"}]},\"version\": \"5.4.11\""
  ",\"peripheral_library\": {\"name\": \"melody\",\"version\": \"NA\"}},\"data_mode"
  "l\": {\"schema_version\": 5},\"motorBench\": {\"commit_id\": \"6062ee969f17e173c"
  "b8502638f1e3c8ee7bea3fb\",\"version\": \"2.45.0\"},\"MCAF\": {\"build\": {\"comm"
  "it_id\": \"116330\",\"date_str\": \"2023 Feb 09\",\"hostname\": \"motor-control-"
  "mcaf-tags-builder-r7-2frc37-1-0ws3m-smcgr-kthrw\",\"time\": 1675959683.33,\"time"
  "_iso\": \"2023-02-09T16:21:23.327489\",\"time_str\": \"2023 Feb 09 16:21\",\"typ"
  "e\": \"release\",\"username\": \"jenkins\",\"version\": \"R7\\/RC37\"},\"build_t"
  "ime\": 1675959683.33,\"build_time_iso\": \"2023-02-09T16:21:23.327489\",\"build_"
  "time_str\": \"2023 Feb 09 16:21\",\"commit_id\": \"116330\",\"version\": \"R7\\/"
  "RC37\"}},\"scdata\": {\"setup\": {\"communications\": {\"baudrate\": 625000},\"a"
  "nalysis\": {\"spindown_time\": {\"units\": \"s\",\"value\": 1.0},\"max_motor_spe"
  "ed\": {\"units\": \"rad\\/s mechanical\",\"value\": 2094.4}},\"calibration\": {"
  "\"vdc\": {\"units\": \"V\",\"value\": 24.0},\"resistor\": {\"units\": \"ohms\","
  "\"value\": 12.0}}}},\"autotune_result\": {\"current\": {\"Kp\": 2.63957830003,\""
  "phase_margin\": 80.0,\"wc\": 1479.84631438,\"Ki\": 3906.17021881,\"pi_phase_lag"
  "\": 45.0},\"velocity\": {\"Kp\": 0.00940228138632,\"phase_margin\": 65.0,\"wc\":"
  " 91.2461550294,\"Ki\": 0.151274800353,\"pi_phase_lag\": 10.0}},\"code_generation"
  "_tag_map\": {\"application\": \"sample\",\"diagnostics\": \"x2cscope\"},\"operat"
  "ing_range\": {\"velocity\": {\"units_qualifier\": \"mechanical\",\"units\": \"ra"
  "d\\/s\",\"minimum\": 104.7198}},\"build\": {\"hardware_spec\": \"mclv2:33ck256mp"
  "508_extopamp_pim\",\"normfactor_associations\": [{\"context\": null,\"annotation"
  "s\": [{\"typerefs\": [\"MCAF_U_CURRENT_ABC\",\"MCAF_U_CURRENT_ALPHABETA\",\"MCAF"
  "_U_CURRENT_DQ\",\"MCAF_U_CURRENT\",\"MCAF_MOTOR_DATA.omegaCtrl.outMin\",\"MCAF_M"
  "OTOR_DATA.omegaCtrl.outMax\"],\"unit\": \"I\",\"q\": 15},{\"typerefs\": [\"MCAF_"
  "MOTOR_DATA.omegaCtrl.integrator\"],\"unit\": \"I\",\"q\": 15},{\"typerefs\": [\""
  "MCAF_U_VOLTAGE_ABC\",\"MCAF_U_VOLTAGE_ALPHABETA\",\"MCAF_U_VOLTAGE_DQ\",\"MCAF_U"
  "_VOLTAGE\",\"MCAF_MOTOR_DATA.idCtrl.outMin\",\"MCAF_MOTOR_DATA.idCtrl.outMax\","
  "\"MCAF_MOTOR_DATA.iqCtrl.outMin\",\"MCAF_MOTOR_DATA.iqCtrl.outMax\"],\"unit\": "
  "\"V\",\"q\": 15},{\"typerefs\": [\"MCAF_MOTOR_DATA.idCtrl.integrator\",\"MCAF_MO"
  "TOR_DATA.iqCtrl.integrator\"],\"unit\": \"V\",\"q\": 31},{\"typerefs\": [\"MCAF_"
  "U_DUTYCYCLE_ABC\"],\"unit\": 1,\"q\": 15},{\"typerefs\": [\"MCAF_U_ANGLE_ELEC\"]"
  ",\"unit\": \"theta_e\",\"q\": 15},{\"typerefs\": [\"MCAF_U_ANGLE_MECH\"],\"unit"
  "\": \"theta_m\",\"q\": 15},{\"typerefs\": [\"MCAF_U_VELOCITY_MECH\"],\"unit\": "
  "\"omega_m\",\"q\": 15},{\"typerefs\": [\"MCAF_U_VELOCITY_ELEC\"],\"unit\": \"ome"
  "ga_e\",\"q\": 15},{\"typerefs\": [\"MCAF_U_VELOCITY_DTHETA_ELEC_DT\"],\"unit\": "
  "\"dtheta_elec_dt\",\"q\": 15},{\"typerefs\": [\"MCAF_U_TEMPERATURE\"],\"unit\": "
  "\"Temperature\",\"q\": 15},{\"typerefs\": [\"MCAF_U_DIMENSIONLESS\",\"MCAF_U_DIM"
  "ENSIONLESS_SINCOS\"],\"unit\": 1,\"q\": 15},{\"typerefs\": [\"MCAF_U_NORMALIZED_"
  "GAIN\"],\"unit\": 1,\"q\": 14}]}]},\"drive\": {\"iout\": {\"measurement\": {\"co"
  "mpensation\": {\"channels\": [\"a\",\"b\"],\"values\": {\"a\": [1.0,0.0],\"b\": "
  "[0.0,1.0]},\"offset\": {\"range\": 0.03125,\"samples\": 128,\"filterGain\": 0.25"
  "}}},\"time_constant\": 1.8413e-07,\"fullscale\": 21.83,\"maximum\": {\"continuou"
  "s\": 14.1421},\"units\": \"A\"},\"estimator\": {\"type\": \"pll\",\"runtimeSelec"
  "t\": false,\"atpll\": {\"tau1\": 0.0001,\"tau2\": 0.00219,\"kpfactor\": 1.9,\"ki"
  "factor\": 30},\"omega1\": 732.0,\"tau\": 0.00219},\"flux_control\": {\"emag_tau"
  "\": 0.001638,\"idref_tau\": 0.006552},\"temperature\": {\"fullscale\": 327.68,\""
  "units\": \"C\"},\"pwm\": {\"adc_sampling_delay\": 0,\"period\": 5e-05,\"duty_cyc"
  "le\": {\"maximum\": 0.975,\"minimum\": 0.009},\"deadtime\": 1e-06},\"mcaf\": {\""
  "adc\": {\"triggerSettings\": {\"noTrigger\": \"NO_TRIGGER\",\"trigger1\": \"PWM1"
  "_TRIGGER1\",\"trigger2\": \"PWM1_TRIGGER2\"},\"channels\": {\"prefix\": \"MCAF_A"
  "DC_\",\"critical\": [\"PHASEA_CURRENT\",\"PHASEB_CURRENT\",\"PHASEC_CURRENT\",\""
  "DCLINK_CURRENT\",\"DCLINK_VOLTAGE\"],\"required\": {\"single_channel\": [\"DCLIN"
  "K_CURRENT\",\"DCLINK_VOLTAGE\",\"POTENTIOMETER\"],\"dual_channel\": [\"PHASEA_CU"
  "RRENT\",\"PHASEB_CURRENT\",\"DCLINK_VOLTAGE\",\"POTENTIOMETER\"],\"triple_channe"
  "l\": [\"PHASEA_CURRENT\",\"PHASEB_CURRENT\",\"PHASEC_CURRENT\",\"DCLINK_VOLTAGE"
  "\",\"POTENTIOMETER\"]},\"optional\": [\"PHASEA_VOLTAGE\",\"PHASEB_VOLTAGE\",\"PH"
  "ASEC_VOLTAGE\",\"BRIDGE_TEMPERATURE\",\"ABSREF_VOLTAGE\"],\"fullList\": [{\"name"
  "\": \"PHASEA_CURRENT\",\"c_fragment\": \"IphaseA\",\"description\": \"phase A cu"
  "rrent\"},{\"name\": \"PHASEB_CURRENT\",\"c_fragment\": \"IphaseB\",\"description"
  "\": \"phase B current\"},{\"name\": \"PHASEC_CURRENT\",\"c_fragment\": \"IphaseC"
  "\",\"description\": \"phase C current\"},{\"name\": \"PHASEA_VOLTAGE\",\"c_fragm"
  "ent\": \"VphaseA\",\"description\": \"phase A voltage\"},{\"name\": \"PHASEB_VOL"
  "TAGE\",\"c_fragment\": \"VphaseB\",\"description\": \"phase B voltage\"},{\"name"
  "\": \"PHASEC_VOLTAGE\",\"c_fragment\": \"VphaseC\",\"description\": \"phase C vo"
  "ltage\"},{\"name\": \"DCLINK_CURRENT\",\"c_fragment\": \"Ibus\",\"description\":"
  " \"DC link current\"},{\"name\": \"DCLINK_VOLTAGE\",\"c_fragment\": \"Dclink\","
  "\"description\": \"DC link voltage\"},{\"name\": \"POTENTIOMETER\",\"c_fragment"
  "\": \"Potentiometer\",\"description\": \"potentiometer voltage\"},{\"name\": \"B"
  "RIDGE_TEMPERATURE\",\"c_fragment\": \"BridgeTemperature\",\"description\": \"bri"
  "dge temperature voltage\"},{\"name\": \"ABSREF_VOLTAGE\",\"c_fragment\": \"Absol"
  "uteReferenceVoltage\",\"description\": \"absolute reference voltage\"}]}}},\"met"
  "adata\": {\"name\": \"dsPIC33CK Low Voltage Motor Control Board\",\"id\": \"lvmc"
  "-33ck\"},\"vdc\": {\"nominal\": 24.0,\"time_constant\": 0.0003147,\"fullscale\":"
  " 71.3,\"maximum\": 48.0,\"units\": \"V\",\"minimum\": 12.0},\"configuration\": {"
  "\"metadata\": {\"capability\": {\"adc\": {\"channel\": {\"PHASEB_VOLTAGE\": \"AN"
  "23\",\"PHASEB_CURRENT\": \"AN1\",\"PHASEA_VOLTAGE\": \"AN17\",\"PHASEC_CURRENT\""
  ": \"AN10\",\"POTENTIOMETER\": \"AN11\",\"BRIDGE_TEMPERATURE\": \"AN12\",\"DCLINK"
  "_VOLTAGE\": \"AN15\",\"PHASEA_CURRENT\": \"AN0\",\"PHASEC_VOLTAGE\": \"AN22\",\""
  "DCLINK_CURRENT\": \"AN4\"}},\"opamp\": \"internal\",\"buttonCount\": 2.0,\"curre"
  "nt_measure\": {\"a\": true,\"b\": true,\"c\": true,\"dc\": true}},\"scaling\": {"
  "\"temperature\": {\"bridge\": {\"offset\": 5000.0,\"gain\": 0.50354}}},\"periphe"
  "rals\": {\"adc\": {\"core\": {\"names\": [\"Core0\",\"Core1\",\"SharedCore\"]}}}"
  ",\"pim\": {\"algorithm\": {\"single_channel\": {\"supported\": true}}},\"device"
  "\": \"33ck256mp508\",\"board\": {\"id\": \"lvmc-33ck\"}},\"peripherals\": {\"adc"
  "\": {\"requestedDedCoreSamplingTimeData\": [{\"core\": \"Core0\",\"requestedSamp"
  "lingTime_us\": 0.3},{\"core\": \"Core1\",\"requestedSamplingTime_us\": 0.3}],\"d"
  "ataOutputFormat\": \"Fractional\",\"channelConfig\": [{\"channel\": \"AN0\",\"si"
  "gn\": \"signed\",\"core\": \"Core0\",\"customName\": \"MCAF_ADC_PHASEA_CURRENT\""
  ",\"inverted\": true},{\"channel\": \"AN1\",\"sign\": \"signed\",\"core\": \"Core"
  "1\",\"customName\": \"MCAF_ADC_PHASEB_CURRENT\",\"inverted\": true},{\"channel\""
  ": \"AN10\",\"sign\": \"signed\",\"core\": \"Shared\",\"customName\": \"MCAF_ADC_"
  "PHASEC_CURRENT\",\"inverted\": true},{\"channel\": \"AN4\",\"sign\": \"signed\","
  "\"core\": \"Shared\",\"customName\": \"MCAF_ADC_DCLINK_CURRENT\",\"inverted\": f"
  "alse},{\"channel\": \"AN15\",\"sign\": \"signed\",\"core\": \"Shared\",\"customN"
  "ame\": \"MCAF_ADC_DCLINK_VOLTAGE\"},{\"channel\": \"AN11\",\"sign\": \"signed\","
  "\"core\": \"Shared\",\"customName\": \"MCAF_ADC_POTENTIOMETER\"},{\"channel\": "
  "\"AN12\",\"sign\": \"unsigned\",\"core\": \"Shared\",\"customName\": \"MCAF_ADC_"
  "BRIDGE_TEMPERATURE\"},{\"channel\": \"AN17\",\"sign\": \"unsigned\",\"core\": \""
  "Shared\",\"customName\": \"MCAF_ADC_PHASEA_VOLTAGE\"},{\"channel\": \"AN23\",\"s"
  "ign\": \"unsigned\",\"core\": \"Shared\",\"customName\": \"MCAF_ADC_PHASEB_VOLTA"
  "GE\"},{\"channel\": \"AN22\",\"sign\": \"unsigned\",\"core\": \"Shared\",\"custo"
  "mName\": \"MCAF_ADC_PHASEC_VOLTAGE\"}],\"customName\": \"MCC_ADC\",\"interruptDr"
  "iven\": false,\"requestedSharedSamplingTime_us\": 0.3,\"resolution\": 12.0},\"co"
  "mparator\": {\"customName\": \"MCC_CMP\",\"dacOutputEnable\": false,\"nonInverte"
  "dSourceSelected\": \"CMP1C\",\"outputPolarity\": \"Non-Inverted\",\"dacDataValue"
  "s\": {\"dataHigh\": 3205.0},\"interruptDriven\": false},\"timer\": [{\"requested"
  "TimerPeriod_ms\": 1.0,\"customName\": \"MCC_TMR_TICK\",\"interruptDriven\": true"
  "},{\"clkSrc\": \"FCY\",\"customName\": \"MCC_TMR_PROFILE\",\"interruptDriven\": "
  "false,\"clkPrescaler\": 1.0,\"periodCount\": 65535.0}],\"oscillator\": {\"clockS"
  "ource\": \"FRC Oscillator with PLL\",\"requestedSystemFrequency_Hz\": 0.0,\"defa"
  "ultValue\": \"max-frequency\",\"setMaximumSystemFrequency\": true,\"clockSourceF"
  "requency\": 8000000.0},\"opamp\": [{\"instance\": 1.0,\"enable\": true,\"customN"
  "ame\": \"MCC_OPA_IA\"},{\"instance\": 2.0,\"enable\": true,\"customName\": \"MCC"
  "_OPA_IB\"},{\"instance\": 3.0,\"enable\": true,\"customName\": \"MCC_OPA_IDC\"}]"
  ",\"qei\": [{\"noiseFilterEnable\": false,\"pinMapping\": [{\"pin\": \"RC12\",\"f"
  "unctionName\": \"A\",\"direction\": \"input\"},{\"pin\": \"RC13\",\"functionName"
  "\": \"B\",\"direction\": \"input\"},{\"pin\": \"RC14\",\"functionName\": \"INDX"
  "\",\"direction\": \"input\"}],\"qeiOperationMode\": \"Modulo Count mode\",\"inde"
  "xPulseCaptureEnable\": false,\"homePulseCaptureEnable\": false,\"homePulsePolari"
  "ty\": false,\"customName\": \"MCC_QEI\",\"indexPulsePolarity\": false}],\"wdt\":"
  " {\"wdtEnable\": true,\"requestedWdtPeriod_ms\": 1.0,\"wdtMode\": \"Non-Window m"
  "ode\",\"wdtEnableType\": \"Software\"},\"pwm\": {\"synchronousUpdate\": true,\"d"
  "uty_cycle\": {\"maximum\": 0.975,\"minimum\": 0.009},\"requestedDeadTime_us\": {"
  "\"defaultValue\": 1.0,\"maximum\": 6.0,\"minimum\": 0.67},\"customName\": \"MCC_"
  "PWM\",\"generatorMapping\": [{\"name\": \"MOTOR1_PHASE_A\",\"generator\": 1.0},{"
  "\"name\": \"MOTOR1_PHASE_B\",\"generator\": 2.0},{\"name\": \"MOTOR1_PHASE_C\","
  "\"generator\": 4.0}],\"interruptDriven\": false,\"faultInputPolarity\": \"Active"
  "-high\",\"faultInput\": {},\"frequency\": {\"defaultValue\": 20000.0,\"maximum\""
  ": 100000.0,\"minimum\": 1000.0},\"faultInputSource\": \"CMP1 Output\",\"polarity"
  "\": {\"lower\": \"Active-high\",\"upper\": \"Active-high\"}},\"uart\": {\"baudRa"
  "te\": 115200.0,\"pinMapping\": [{\"name\": \"TX\",\"pinSelected\": \"RD13\"},{\""
  "name\": \"RX\",\"pinSelected\": \"RD14\"}],\"stopBits\": 1.0,\"parity\": \"None"
  "\",\"dataSize\": 8.0,\"customName\": \"MCC_UART\",\"interruptDriven\": false},\""
  "gpio\": [{\"isWeakPullUp\": false,\"pinSelected\": \"RE6\",\"interruptOnChange\""
  ": \"none\",\"isWeakPullDown\": false,\"customName\": \"MCAF_LED1\",\"isAnalogPin"
  "\": false,\"direction\": \"output\",\"isOpenDrain\": false},{\"isWeakPullUp\": f"
  "alse,\"pinSelected\": \"RE7\",\"interruptOnChange\": \"none\",\"isWeakPullDown\""
  ": false,\"customName\": \"MCAF_LED2\",\"isAnalogPin\": false,\"direction\": \"ou"
  "tput\",\"isOpenDrain\": false},{\"isWeakPullUp\": false,\"pinSelected\": \"RE11"
  "\",\"interruptOnChange\": \"none\",\"isWeakPullDown\": false,\"customName\": \"M"
  "CAF_BUTTON1\",\"isAnalogPin\": false,\"direction\": \"input\",\"isOpenDrain\": f"
  "alse},{\"isWeakPullUp\": false,\"pinSelected\": \"RE12\",\"interruptOnChange\": "
  "\"none\",\"isWeakPullDown\": false,\"customName\": \"MCAF_BUTTON2\",\"isAnalogPi"
  "n\": false,\"direction\": \"input\",\"isOpenDrain\": false},{\"isWeakPullUp\": f"
  "alse,\"pinSelected\": \"RE4\",\"interruptOnChange\": \"none\",\"isWeakPullDown\""
  ": false,\"customName\": \"MCAF_TESTPOINT1\",\"isAnalogPin\": false,\"direction\""
  ": \"output\",\"isOpenDrain\": false}]},\"displayName\": \"dsPIC33CK LVMC\",\"nam"
  "e\": \"dsPIC33CK Low Voltage Motor Control (LVMC) Development Board\",\"partNumb"
  "er\": \"DM330031\",\"id\": \"lvmc-33ck\",\"supportedPim\": []},\"idc\": {\"maxim"
  "um\": 2.9,\"units\": \"A\"},\"sampling_time\": {\"current\": 5e-05,\"velocity\":"
  " 0.001},\"processor\": {\"clock_frequency\": 100000000.0,\"pim\": \"PIM\\/DIM No"
  "t Applicable\",\"familyName\": \"dsPIC33CK256MP508\",\"device\": \"dsPIC33CK256M"
  "P508\"},\"vbus\": 24.0},\"config\": {\"ui\": {\"content\": {\"current_measure-me"
  "thod\": \"dual_channel\",\"current_measure-single_channel-minimumTime\": 2.0,\"c"
  "urrent_measure-single_channel-sampleDelay\": 0.0,\"current_measure-opamp-full_in"
  "put_range\": true,\"estimator-type\": \"pll\",\"estimator-active-pll\": false,\""
  "estimator-active-qei\": false,\"estimator-active-atpll\": false,\"estimator-acti"
  "ve-zsmt\": false,\"estimator-active-ideal\": false,\"operation-min_velocity_rati"
  "o\": 0.25,\"operation-startup_velocity_ratio\": 0.2744,\"operation-max_velocity_"
  "ratio\": 1.25,\"operation-fullscale_base_ratio\": 1.5,\"operation-outer_loop_typ"
  "e\": \"velocity\",\"operation-saliency-threshold\": 1.25,\"operation-slewrate-ac"
  "cel\": 0.5,\"operation-slewrate-decel\": 1.0,\"operation-dyn_current_type\": \"n"
  "one\",\"operation-stopping-type\": \"minimal_impact\",\"operation-stopping-close"
  "d_loop_parameters-speed\": 0.05,\"operation-stopping-closed_loop_parameters-time"
  "\": 0.5,\"operation-coastdown-end_velocity\": 0.05,\"operation-coastdown-time\":"
  " 1.2,\"fault_inject-get_tf-div0\": false,\"fault_inject-get_tf-missing_data\": f"
  "alse,\"fault_inject-get_tf-raise_value_error\": false,\"fault_inject-get_tf-rais"
  "e_custom_error\": false,\"fault_inject-tf-tf_null\": false,\"fault_inject-tf-tf_"
  "jy\": false,\"fault_inject-tf-tf_jyex\": false,\"fault_inject-tf-div0\": false,"
  "\"fault_inject-tf-tau\": 0.0,\"flux_control-method\": \"none\",\"flux_control-eq"
  "n_based-ilimit-region_type\": \"quadratic\",\"flux_control-eqn_based-ilimit-id_l"
  "imit\": 0.7,\"flux_control-eqn_based-ilimit-iq_limit\": 0.95,\"flux_control-eqn_"
  "based-fluxweak_enable\": false,\"flux_control-eqn_based-fw-vdq_limit\": 0.95,\"f"
  "lux_control-eqn_based-mtpa_enable\": false,\"deadtimecomp-method\": \"none\",\"d"
  "eadtimecomp-perphase-current_sign_band\": 0.02,\"deadtimecomp-perphase-forward_g"
  "ain\": 0.0,\"deadtimecomp-perphase-feedback_gain\": 0.0,\"fault_detect-margin_uv"
  "\": 2.0,\"fault_detect-margin_ov\": 2.0,\"fault_detect-stall_detect_enable\": tr"
  "ue,\"startup-Istartup\": 0.75,\"startup-t_rampup\": 25.0,\"startup-t_align\": 0."
  "0,\"startup-min_total_accel_time\": 250.0,\"startup-torque_scale_accel\": 0.15,"
  "\"startup-torque_scale_slow_accel\": 0.2,\"startup-t_hold\": 0.0,\"startup-omega"
  "0\": 0.2,\"startup-theta_converge_rate\": 1.0,\"startup-method\": \"classic\",\""
  "startup-damping-Imax\": 0.1,\"startup-damping-gainmax\": 40.0,\"startup-damping-"
  "omega_min\": 0.4,\"overmodulation-vd_limit\": 1.0,\"overmodulation-vq_limit\": 1"
  ".15,\"overmodulation-include_duty_clipping\": true,\"pll-tau\": 2.19,\"pll-omega"
  "1\": 116.5,\"pll-velocity_filter_threshold\": 1.0,\"encoder-lines\": 250.0,\"enc"
  "oder-index_present\": false,\"encoder-tracking_loop-tau\": 1.5,\"encoder-qei_syn"
  "c-method\": \"align\",\"encoder-qei_sync-align-t_align\": 0.5,\"encoder-qei_sync"
  "-align-angle_shift\": 30.0,\"encoder-qei_sync-align-angle_init\": -30.0,\"encode"
  "r-qei_sync-align_sweep-sweep_rate_pow\": 1.0,\"encoder-qei_sync-align_sweep-setu"
  "p_angle\": 45.0,\"encoder-qei_sync-pullout-pullout_slip\": 0.117,\"zsmt-excitati"
  "on-kV\": 0.12,\"zsmt-excitation-kI\": 0.1,\"zsmt-pll-zeta\": 1.5,\"zsmt-pll-tau"
  "\": 10.0,\"zsmt-pll-tau_lpf\": 0.0,\"zsmt-pll-execution_divider\": 2.0,\"zsmt-st"
  "artup-align_delay\": 1.0,\"zsmt-startup-pll_lock_time\": 1.0,\"zsmt-startup-spee"
  "d_limit\": 0.015,\"zsmt-startup-current_limit\": 0.3,\"zsmt-startup-probe_durati"
  "on\": 10.0,\"zsmt-startup-probe_slew_time\": 1.5,\"zsmt-startup-probe_blanking_t"
  "ime\": 4.0,\"zsmt-hybrid-type\": \"minotaur\",\"zsmt-minotaur-voltage_limit-vd\""
  ": 0.45,\"zsmt-minotaur-voltage_limit-vq\": 0.78,\"zsmt-minotaur-converge-angle\""
  ": 10.0,\"zsmt-minotaur-converge-duration\": 2.0,\"zsmt-minotaur-velocity_thresho"
  "ld-slow\": 0.15,\"zsmt-minotaur-velocity_threshold-transition\": 0.2,\"zsmt-mino"
  "taur-velocity_threshold-fast\": 0.25,\"zsmt-angle_correction-current_gain\": 0.0"
  ",\"dyn_current1-peak_factor\": 1.0,\"dyn_current1-horizon_factor\": 1.05,\"dyn_c"
  "urrent1-tau\": 5.0,\"dyn_current1-nsamples\": 128.0,\"voltage_outerloop-tau_lpf"
  "\": 2.0,\"voltage_outerloop-Kp\": 0.1,\"voltage_outerloop-tau\": 100.0,\"mcapi-i"
  "sSquaredTau\": 1.0,\"mcapi-iqTau\": 1.0,\"mcapi-adcIsrUserFunctions_enable\": fa"
  "lse,\"board_service-uiServiceTiming\": 1.0,\"board_service-uiButtonDebounceTime"
  "\": 7.0,\"board_service-uiButtonLongPressTime\": 2.5,\"test_harness-perturbation"
  "_asymmetric\": false,\"adc-vtempbridge\": false,\"adc-temp_bridge_params-thresho"
  "ld\": 50.0,\"adc-temp_bridge_params-tau_lpf\": 10.0,\"adc-temp_bridge_params-sle"
  "wrate\": 4.0,\"adc-vabsref\": false,\"adc-vphasea\": false,\"adc-vphaseb\": fals"
  "e,\"adc-vphasec\": false},\"version\": {\"schema\": 4.0,\"motorBench\": \"???\","
  "\"MCAF\": \"R7\"},\"status\": {\"valid\": true}}}}";